db:
  DB_HOST: 172.26.128.139
  DB_USER: system
  DB_PASSWORD: system123

sql:
  SQL_CMD: |
    select user,
           host
      from mysql.user           

xlsx:
  XLSX_RPT_DIR: xlsx
  XLSX_RPT_PREFIX: 数据入仓离线采集日报
  HEADER_FILL: dae9f8
  DATA_EVEN_FILL: daf2d0
  AUTO_OPEN: true
  AUTO_OPEN_SECS: 40